#!/usr/bin/env python3
"""
Auto-settlement + P&L report for the paper-trade journal (trades.csv).

For every journal row without a result, asks Kalshi for the market's official
settlement (`result: yes|no` on the market object). Once a market reports,
fills in `result` and `pnl_c` exactly like `log_bet.py --settle` would --
no forecasting, no judgment, just the exchange's own outcome. Rows for
still-open months are left alone and retried next run.

Also (re)writes PNL.md: a per-tier scorecard -- signals, settled, hit rate vs
the rate the entry prices implied, and realized P&L pre- and post- estimated
fees. Per-tier is the whole point: each tier is a separate hypothesis
(Tier 1 lag, Tier 2 storm-delivery, Tier 3 ensemble delta, Tier 4 surprise
lag) and the journal exists to tell you which, if any, survives settlement.

Runs in the GitHub Actions cron after each polling pass (cheap: one API call
per distinct unsettled event, nothing at all once everything is settled).

  python3 settle.py            # settle what's settleable, rewrite PNL.md
  python3 settle.py --dry-run  # show what would settle, touch nothing
"""

import argparse
import math
import os
import re
from datetime import datetime, timezone

from scan_monthly import get, API, THRESH_RE
from log_bet import read_rows, write_rows

PNL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "PNL.md")
TIER_RE = re.compile(r"Tier\s*(\d)", re.I)

TIER_LABEL = {
    "1": "Tier 1 FLOOR-LOCK (certain lag)",
    "2": "Tier 2 APPROACH (storm delivery)",
    "3": "Tier 3 NEXT-LEVEL (ensemble delta)",
    "4": "Tier 4 SURPRISE-LAG (reaction speed)",
    "manual": "Manual / other",
}


def event_results(event):
    """{threshold: 'yes'|'no'} for every market in the event that has an
    official settlement result. Markets still open/unsettled are absent."""
    d = get(f"{API}/markets?limit=100&event_ticker={event}")
    out = {}
    for m in d.get("markets", []):
        sub = m.get("yes_sub_title") or m.get("subtitle") or ""
        mt = THRESH_RE.search(sub)
        if not mt:
            continue
        r = (m.get("result") or "").lower()
        if r in ("yes", "no"):
            out[float(mt.group(1))] = r
    return out


def est_fee_c(price_c, count):
    """Kalshi trading fee estimate: ceil(0.07 * count * p * (1-p)) dollars,
    expressed in cents. Verify against their current schedule before trusting
    to the cent -- this is a buffer, not an invoice."""
    p = price_c / 100.0
    return math.ceil(7 * count * p * (1 - p))


def tier_of(row):
    m = TIER_RE.search(row.get("note") or "")
    return m.group(1) if m else "manual"


def settle_all(dry_run):
    rows = read_rows()
    pending = [r for r in rows if not r["result"] and r.get("event")]
    settled_now = 0
    cache = {}
    for r in pending:
        ev = r["event"]
        if ev not in cache:
            try:
                cache[ev] = event_results(ev)
            except Exception as e:
                print(f"{ev}: lookup failed ({type(e).__name__}: {e}) -- retry next run")
                cache[ev] = {}
        res = cache[ev].get(float(r["threshold"]))
        if res is None:
            continue  # not settled yet (or rung not found) -- leave for later
        won = res == r["side"]
        price = int(float(r["price_paid_c"]))
        count = int(float(r["count"] or 1))
        pnl = (100 - price if won else -price) * count
        print(f"row {r['id']}: {r['series']} >{r['threshold']} settled {res.upper()} "
              f"-> {'WIN' if won else 'LOSS'} {pnl:+d}c (paid {price}c x{count})")
        if not dry_run:
            r["result"], r["pnl_c"] = res, str(pnl)
        settled_now += 1
    if settled_now and not dry_run:
        write_rows(rows)
    return rows, settled_now


def write_report(rows):
    tiers = {}
    for r in rows:
        tiers.setdefault(tier_of(r), []).append(r)
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# Paper P&L by tier",
        "",
        f"_Auto-generated by settle.py -- last update {now}. Fills assumed at the",
        "alert ask; fees are the ~7%·p·(1−p) estimate. Small samples lie: judge a",
        "tier on a season, not a week._",
        "",
        "| tier | signals | settled | wins | hit rate | implied | pnl (c) | pnl after est. fees (c) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    tot_pnl = tot_net = 0
    for key in sorted(tiers, key=lambda k: (k == "manual", k)):
        rs = tiers[key]
        done = [r for r in rs if r["result"]]
        wins = sum(1 for r in done if r["result"] == r["side"])
        pnl = sum(int(r["pnl_c"]) for r in done)
        fees = sum(est_fee_c(int(float(r["price_paid_c"])),
                             int(float(r["count"] or 1))) for r in done)
        # what the entry prices said the hit rate should be (buy-yes rows)
        implied = (sum(float(r["price_paid_c"]) for r in done) / len(done)
                   if done else 0.0)
        hit = f"{wins}/{len(done)}" if done else "--"
        hitpc = f" ({100 * wins / len(done):.0f}%)" if done else ""
        lines.append(
            f"| {TIER_LABEL.get(key, key)} | {len(rs)} | {len(done)} | {wins} "
            f"| {hit}{hitpc} | {implied:.0f}c | {pnl:+d} | {pnl - fees:+d} |")
        tot_pnl += pnl
        tot_net += pnl - fees
    lines += ["",
              f"**Total realized: {tot_pnl:+d}c ({tot_net:+d}c after est. fees)**",
              "",
              "Reading it: a tier only 'works' if its hit rate beats the implied",
              "column by more than the fees eat. Open (unsettled) rows are counted",
              "in *signals* but not in P&L.", ""]
    with open(PNL_PATH, "w") as f:
        f.write("\n".join(lines))
    print(f"wrote {PNL_PATH}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true",
                    help="show what would settle; don't write files")
    a = ap.parse_args()
    rows, n = settle_all(a.dry_run)
    print(f"{n} row(s) settled this pass; "
          f"{sum(1 for r in rows if not r['result'])} still open")
    if not a.dry_run:
        write_report(rows)


if __name__ == "__main__":
    main()
